spring:
  emily:
    datasource:
      config:
        pool-a:
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://localhost:3306/pool-a?useUnicode=true&characterEncoding=utf8
          username: root
          password: 123456
          type: com.alibaba.druid.pool.DruidDataSource
        pool-b:
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://localhost:3306/pool-b?useUnicode=true&characterEncoding=utf8
          username: root
          password: 123456
          type: com.alibaba.druid.pool.DruidDataSource


mybatis:

  #  config-location: classpath:mybatis/mybatis-config.xml
  # 配置mybatis的mapper文件
  mapper-locations: classpath:mapper/*.xml
  # Sql语句正茬查不出数据，显示数据结构和接口返回数据不匹配，使用这个配置将下划线的字段改为驼峰命名
  configuration:
    mapUnderscoreToCamelCase: true